apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-fastapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-fastapi
  template:
    metadata:
      labels:
        app: hello-fastapi
    spec:
      containers:
      - name: hello-fastapi-container
        image: bernardomeucci/hello-fastapi-app:c2040aac227df7f5fea5228d86b333b3071b8a4e
        ports:
        - containerPort: 8000